[EXP]
root = ./results/compare/
databases = ['emodb', 'polish', 'emovo']
[DATA]
emodb = /home/felix/data/audb/emodb/
polish = ./databases/polish-emotional-speech/
target = emotion
emodb.mapping = {'anger':'angry', 'happiness':'happy', 'sadness':'sad', 'neutral':'neutral'}
polish.mapping = {'anger':'angry', 'joy':'happy', 'sadness':'sad', 'neutral':'neutral'}
emovo = ../nkululeko/data/emovo/emovo.csv
emovo.type = csv
emovo.absolute_path = False
emovo.mapping = {'anger':'angry', 'happiness':'happy', 'sadness':'sad', 'neutral':'neutral'}
labels = ['neutral', 'happy', 'sad', 'angry']
[FEATS]
type = ['os']
print_feats = False
[MODEL]
type = svm
C_val = 10
; type = mlp
; layers = {'l1':128, 'l2':16}
; device = cpu
; save = True
#patience = 5
[PLOT]
best_model = True
epoch_progression = True
